name: Release Actions

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 A ${{ github.event_name }} event running on a ${{ runner.os }} server."
      - run: echo "🔎 The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.2.0'

      - run: echo "📦 Installing packages" && yarn install --frozen-lockfile
      - run: echo "🖥️ Linting" && yarn nx run-many --all --target=lint --color
      - run: echo "🖥️ Type checking" && yarn nx run-many --all --target=type-check --color
      - run: echo "🖥️ Building" && yarn nx run-many --all --target=build --color
      - run: echo "🖥️ Unit testing" && yarn nx run-many --all --target=test --ci --code-coverage --color
      - run: echo "🖥️ E2E testing" && yarn nx run-many --all --target=e2e --color

      - run: echo "✅ Congratulations!"
